language: node_js
node_js:
  - '0.10'
env:
  global:
    secure: "XTNI1D6bxcGseQY7yZSqk+cWD0kJt2w+zSgXfMbJ6XEtQdBe+msRXlj0uL7MCnaEnVIyiFv6vn0ydb6BRHWk7PHhjqbcGzgrBEKS+/ro26JhwpSqlWdtHoVZbXa/N854jOuVbcVn4iTHicjGxergKlHBJUlj1+nVVim24D6khrg="
    secure: "MoxnsViaBa/tZyVE5sDAmzv8rhFXmsatYdTf5UdjWauGyyAlE2H4rpme3KyH3QJsRfeA2S30Mfe0Du7eY47Q/FcOwCSdT6qNmnOWM4AivkfiFsRSmoJyIaV+WYyZNsNJOpXUlIyL/9z2Djwytfw1fCkz5ViFEWTCFEjcCPiAjBM="
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm test
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
