language: node_js
node_js:
  - '0.10'
env:
  global:
    - API_HOST: "http://staging.api.anyfetch.com"
    - secure: "JZD117XvW5EFVFcjIlJFpFfUYujXy0r4tiBeWbolKznrfLFSvg9A+IVPd9PC/LR/wFksnd6wCyZ9lzBsavR+lrHzASfM5UBAYdlnC+ehOglba18Y3HdkU7t+vYYeFKREF0rfi0JQ21TwFyXpKv+xFTGp+h8Jc8aHn7BpLxqcirU="
    - secure: "me5BMPhjVfJHPSxDkzaH2SO0c5tWdVYC4k1C9cim7rmJJ5RpOFmQiNvXPaHf3fYhxMaJ8iYZKum4tPmhdVRRIta6YDP/syW+2UV8xGE0zKiGAPkM3F0icUpTIxXlrs2DAMVNHPxHPDKkom3MJ9jmPo7ZpGPSzHY4nsIJ88maSpg="
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm test
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
