language: node_js
node_js:
  - '0.10'
env:
  global:
    secure: "JZD117XvW5EFVFcjIlJFpFfUYujXy0r4tiBeWbolKznrfLFSvg9A+IVPd9PC/LR/wFksnd6wCyZ9lzBsavR+lrHzASfM5UBAYdlnC+ehOglba18Y3HdkU7t+vYYeFKREF0rfi0JQ21TwFyXpKv+xFTGp+h8Jc8aHn7BpLxqcirU="
    secure: "fde4hIF0xkPRo7qv4OQY4Elg88A9G1qQewWRKNmS36UwtN8PskXfl3b88YOhF1lfMcaie/u7BC1bOWvLFtB2Deq1HlbGSW7ThIkI+uYfrC2SEkUR4v1LQ42nM7chGccG2jVzdvdMpA6mknhzp7iueFAGZkBdR1GveHOYuKCe1Ns="
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm test
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
